version: '1.0'
name: "Image Calories Calculator"
workflows:
  - id: calculate-calories-in-images
    path: ./calculate-calories-in-images.yaml
    enabled: true
    webhookTimeout: 30000
server:
  port: 13000
  host: 0.0.0.0
  frontend: ./frontend
defaults:
  webhookTimeout: 30000
