packages:
  - packages/*
  - packages/*/ui
  - packages/*/server
  - packages/*/core
  - packages/*/app
  - packages/*/frontend-builder

onlyBuiltDependencies:
  - esbuild
  - nx


recursiveInstall: true
injectWorkspacePackages: true