@host = http://localhost
@port = 3000

# =============================================================================
# Sample API Requests - Bits Framework
# =============================================================================
# 
# This file contains sample API requests for testing with Bits modules.
#
# =============================================================================

### Execute module - Bits HTTP
POST {{host}}:{{port}}/habits/api/execute
Content-Type: application/json

{
  "module": "bits/@ha-bits/bit-http",
  "params": {
    "method": "GET",
    "url": "https://httpbin.org/get"
  }
}


###
GET {{host}}:{{port}}/habits/api/modules
Content-Type: application/json


###
GET {{host}}:{{port}}/habits/api/modules/check/bits/@ha-bits%2Fbit-http


###
GET {{host}}:{{port}}/habits/api/modules/schema/bits/@ha-bits%2Fbit-http


###
GET {{host}}:{{port}}/habits/api/modules/schema/bits/@ha-bits%2Fbit-intersect


###
POST {{host}}:{{port}}/habits/api/forms/populate-options
Content-Type: application/json

{
  "framework": "bits",
  "moduleId": "@ha-bits/bit-intersect",
  "actionName": "send_prompt",
  "fieldName": "model",
  "currentValues": {}
}
