/**
 * Tauri README template generator
 */

export interface TauriReadmeOptions {
  platform: 'desktop' | 'mobile';
  appName: string;
  backendUrl: string;
  desktopPlatform?: string;
  mobileTarget?: 'ios' | 'android' | 'both';
}

/**
 * Generate README content for Tauri project
 */
export function getTauriReadme(options: TauriReadmeOptions): string {
  const { platform, appName, backendUrl, mobileTarget } = options;

  if (platform === 'mobile') {
    return getMobileReadme(appName, backendUrl, mobileTarget!);
  } else {
    return getDesktopReadme(appName, backendUrl);
  }
}

function getMobileReadme(
  appName: string,
  backendUrl: string,
  mobileTarget: 'ios' | 'android' | 'both'
): string {
  return `# ${appName} - Tauri Mobile App

Generated by Habits for ${mobileTarget === 'both' ? 'iOS and Android' : mobileTarget}.

## Prerequisites

- Node.js 18+
- Rust toolchain (install from https://rustup.rs/)
${
  mobileTarget === 'ios' || mobileTarget === 'both'
    ? `- Xcode 14+ (for iOS, macOS only)
- CocoaPods: \`sudo gem install cocoapods\``
    : ''
}
${
  mobileTarget === 'android' || mobileTarget === 'both'
    ? `- Java 17+ (for Android)
  - Install: \`brew install openjdk@17\` (macOS) or download from Oracle
  - Set JAVA_HOME: \`export JAVA_HOME=$(/usr/libexec/java_home -v 17)\` (macOS)
- Android SDK & NDK
  - Install Android Studio or Android Command Line Tools
  - Set ANDROID_HOME: \`export ANDROID_HOME=$HOME/Library/Android/sdk\` (macOS)
  - Install NDK: In Android Studio > SDK Manager > SDK Tools > NDK`
    : ''
}

## Setup

\`\`\`bash
# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install Tauri CLI & dependencies
npm install

# Initialize mobile platforms
${mobileTarget === 'ios' || mobileTarget === 'both' ? 'npx tauri ios init' : ''}
${mobileTarget === 'android' || mobileTarget === 'both' ? 'npx tauri android init' : ''}
\`\`\`

## Development

\`\`\`bash
${mobileTarget === 'ios' || mobileTarget === 'both' ? '# Run on iOS simulator\nnpm run ios' : ''}
${mobileTarget === 'android' || mobileTarget === 'both' ? '# Run on Android emulator\nnpm run android' : ''}
\`\`\`

## Build

\`\`\`bash
${mobileTarget === 'ios' || mobileTarget === 'both' ? '# Build for iOS\nnpm run build:ios' : ''}
${mobileTarget === 'android' || mobileTarget === 'both' ? '# Build for Android\nnpm run build:android' : ''}
\`\`\`

## Output Locations

${mobileTarget === 'ios' || mobileTarget === 'both' ? '- iOS: \`src-tauri/gen/apple/\`' : ''}
${mobileTarget === 'android' || mobileTarget === 'both' ? '- Android APK: \`src-tauri/gen/android/app/build/outputs/apk/\`' : ''}

## Backend URL

This app connects to: ${backendUrl}

To change the backend URL, edit \`tauri.conf.json\` and update the \`plugins.http.scope\` array.
`;
}

function getDesktopReadme(appName: string, backendUrl: string): string {
  return `# ${appName} - Tauri Desktop App

This is a Tauri desktop application generated by Habits.

## Prerequisites

- Rust toolchain (install from https://rustup.rs/)
- Node.js 18+
${process.platform === 'darwin' ? '- Xcode Command Line Tools (macOS)' : ''}
${process.platform === 'win32' ? '- Microsoft Visual Studio C++ Build Tools (Windows)' : ''}
${
  process.platform === 'linux'
    ? '- System dependencies: `sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev`'
    : ''
}

## Setup

\`\`\`bash
# Install dependencies
npm install

# Install Rust (if not already installed)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
\`\`\`

## Development

\`\`\`bash
npm run dev
\`\`\`

## Build

\`\`\`bash
# Build release binary
npm run build

# Build debug binary (faster)
npm run build:debug
\`\`\`

## Output Locations

After building, the application will be in:
- macOS: \`src-tauri/target/release/bundle/dmg/\`
- Windows: \`src-tauri/target/release/bundle/msi/\` or \`src-tauri/target/release/bundle/nsis/\`
- Linux: \`src-tauri/target/release/bundle/appimage/\`, \`deb/\`, or \`rpm/\`

## Backend URL

This app connects to: ${backendUrl}

To change the backend URL, edit \`tauri.conf.json\` and update the \`plugins.http.scope\` array.
`;
}
