/**
 * Default modules list for habits.
 * This is the canonical source of truth for available modules.
 * Used by:
 * - implicit `habits base` project setup to populate modules.json
 * - moduleLoader as fallback when modules.json doesn't exist
 *
 * AUTO-GENERATED by scripts/generate-bits.ts — do not edit manually.
 */

export interface ModuleDefinition {
  framework: string;
  source: 'npm' | 'github';
  repository: string;
}

export interface ModulesConfig {
  modules: ModuleDefinition[];
}

/**
 * Default modules configuration.
 * All standard bits modules available from npm.
 */
export const defaultModules: ModulesConfig = {
  modules: [
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-agent' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-ai' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-any-of' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-auth' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-cookie' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-crm' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-database' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-database-mongodb' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-database-sql' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-discord' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-dropbox' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-email' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-file-hosting' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-filesystem' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-github' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-gohighlevel' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-google-calendar' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-google-drive' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-google-sheets' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-hello-world' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-http' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-httpbin' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-hubspot' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-if' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-instagram' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-intersect' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-invoice' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-jsonplaceholder' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-linkedin' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-local-ai' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-location' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-logger' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-loop' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-markdown-to-html' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-oauth-mock' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-ocr' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-onedrive' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-openai' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-pdf' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-pouch' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-qr' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-rss' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-salesforce' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-scheduler' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-shell' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-slack' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-smart-home' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-sms' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-snov' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-string' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-stripe' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-sumsub' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-system-settings' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-tasks' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-telegram' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-text' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-twitter' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-voice' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-web-scraper' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-whatsapp' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-wifi' },
    { framework: 'bits', source: 'npm', repository: '@ha-bits/bit-wise' },
  ],
};
