@host = localhost
@port = 13000

@intersect_api_key={{$dotenv INTERSECT_API_KEY}}

@workflow_name = minimal-business-intersect


### Health Check
# @name healthCheck
GET http://{{host}}:{{port}}/health

?? status == 200


### List all workflows
# @name listWorkflows
GET http://{{host}}:{{port}}/misc/workflows

?? status == 200


### Get workflow details
# @name getWorkflowDetails
GET http://{{host}}:{{port}}/misc/workflow/{{workflow_name}}

?? status == 200


### Execute Marketing Campaign
POST http://{{host}}:{{port}}/api/{{workflow_name}}
Content-Type: application/json
Host: localhost:11000
Cookie: token={{intersect_api_key}}
# Authorization: ""
{
  "prompt": "Launch campaign for a new eco-friendly water bottle"
}

?? status >= 200
?? status < 300