/**
 * N8N Types Index
 * 
 * Re-exports all types from split modules for backwards compatibility.
 * Note: Some types are duplicated across modules. This index carefully
 * manages exports to avoid conflicts.
 */

// Utility types - base types used everywhere
export * from './utility-types';

// Credential types - authentication and credentials  
export * from './credential-types';

// Execution types - execution context and functions
// Using explicit exports to avoid conflicts with node-types
export {
    IConnection,
    NodeInputConnections,
    INodeConnection,
    INodeConnections,
    IConnections,
    IExecuteResponsePromiseData,
    IRunNodeResponse,
    ISourceDataConnections,
    IExecuteData,
    IContextObject,
    IExecuteContextData,
    IHttpRequestMethods,
    IHttpRequestOptions,
    IRequestOptions,
    PaginationOptions,
    IN8nHttpResponse,
    IN8nHttpFullResponse,
    IN8nRequestOperations,
    IN8nRequestOperationPaginationBase,
    IN8nRequestOperationPaginationGeneric,
    IN8nRequestOperationPaginationOffset,
    DeclarativeRestApiSettings,
    EnsureTypeOptions,
    IGetNodeParameterOptions,
    IExecuteWorkflowInfo,
    BaseHelperFunctions,
    FileSystemHelperFunctions,
    BinaryHelperFunctions,
    DeduplicationScope,
    DeduplicationItemTypes,
    DeduplicationMode,
    IProcessedDataLatest,
    IProcessedDataEntries,
    IDeduplicationOutput,
    IDeduplicationOutputItems,
    ICheckProcessedOptions,
    DeduplicationHelperFunctions,
    RequestHelperFunctions,
    SSHCredentials,
    SSHTunnelFunctions,
    CronExpression,
    CronContext,
    Cron,
    SchedulingFunctions,
    NodeTypeAndVersion,
    FunctionsBase,
    ContextType,
    DataTableProxyProvider,
    DataTableProxyFunctions,
    IExecuteFunctions,
    IExecuteSingleFunctions,
    ISupplyDataFunctions,
    IExecutePaginationFunctions,
    ILoadOptionsFunctions,
    ILocalLoadOptionsFunctions,
    IWorkflowLoader,
    IPollFunctions,
    ITriggerFunctions,
    IHookFunctions,
    IWebhookFunctions,
    IAllExecuteFunctions,
    FieldValueOption,
    IWorkflowNodeContext,
    IPostReceiveBase,
    IPostReceiveBinaryData,
    IPostReceiveFilter,
    IPostReceiveLimit,
    IPostReceiveRootProperty,
    IPostReceiveSet,
    IPostReceiveSetKeyValue,
    IPostReceiveSort,
    PostReceiveAction,
    PreSendAction,
    IWorkflowMetadata,
    WorkflowActivateMode,
    IWorkflowBase,
    IPinData,
    IWorkflowSettings,
    WorkflowSettings,
    WorkflowFEMeta,
    IRun,
    IRunData,
    ITaskSubRunMetadata,
    RelatedExecution,
    ITaskMetadata,
    ITaskStartedData,
    ITaskData,
    ISourceData,
    StartNodeData,
    ITaskDataConnections,
    IWaitingForExecution,
    ITaskDataConnectionsSource,
    IWaitingForExecutionSource,
    ExecuteWorkflowData,
    NodeExecutionWithMetadata,
    AiEvent,
    ProxyInput,
    IWorkflowDataProxyData,
    IWorkflowDataProxyAdditionalKeys,
    IWorkflowExecuteAdditionalData,
    AiAgentRequest,
    ExecuteWorkflowOptions,
    IWorkflowExecutionDataProcess,
    IDestinationNode,
    IProcessedDataConfig,
    IDataDeduplicator,
    ICheckProcessedContextData,
} from './execution-types';

// Node types - node definitions and properties
export * from './node-types';
