name: NPM Publish

on:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - 'release/**'

permissions:
  contents: read
  id-token: write

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          cache: true
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: npx tsx scripts/npm-publish.ts | npx tsx scripts/log-sanitizer.ts

